name    'puppet-windows_common'
version '0.1.0'
source 'https://github.com/openstack-hyper-v/puppet-windows_common.git'
author 'Peter Pouliot <peter@pouliot.net>'
license 'Apache License, Version 2.0'
summary 'Common Windows Tasks automated with Puppet'
description 'Common Windows Tasks automated with Puppet'
project_page 'https://github.com/openstack-hyper-v/puppet-windows_common'
dependency 'joshcooper/powershell'
dependency 'basti1302/windows_path'
dependency 'puppetlabs/registry'
dependency 'puppetlabs/stdlib'
